### ISSUE TITLE
Feature Request: Error Bounds + Linear Error Propogation

### ISSUE THREAD

**Issue by mvcisback** [bjornbm/dimensional-tf#2]
It would be nice to have direct support for encoding error bounds and error propagation.

Without dimensional, I've used http://rosettacode.org/wiki/Numeric_error_propagation#Haskell, but that doesn't seem to directly transfer

**Comment by bjornbm** [comment]
All dimensional requires for representing the value is an instance of `Num` (or `Fractional` or “greater” depending on what you need to do) so you should be able to use the it with the `Error a` type from rosettacode.org. Here is an example (not tested):

```haskell
distance = Error 10 0.1 *~ meter
time = Error 2 0.001 *~ second
velocity = distance / time
raw_vel = velocity /~ (meter / second)
```

Where raw_vel would be of e.g. type `Error Double` (perhaps a type annotation is required to fix the `Double`). If this doesn't work for you or if you had something different in mind please post a follow-up.

**Comment by mvcisback** [comment]
@bjornbm 
Ah, ok. That ended up working just fine, thanks.
